參考資料:
    
1. https://www.youtube.com/watch?v=pVfj6mxhdMw&t=
2. https://ithelp.ithome.com.tw/articles/10209593
3. https://www.youtube.com/watch?v=9wV1VxlfBlI
4. https://wiki.mbalib.com/zh-tw/Dijkstra%E7%AE%97%E6%B3%95
5. https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/434938/
6. https://www.youtube.com/watch?v=HtxN3v321HU
7. https://www.youtube.com/watch?v=wuU4DDEUu1w
8. https://www.youtube.com/watch?v=71UQH7Pr9kU
9. https://blog.csdn.net/luomingjun12315/article/details/47700237
10. https://www.youtube.com/watch?v=-E42M_yDWzI

原理說明:

Dijkstra演算法，又稱最短路徑演算法，是用來計算某一個節點到其他所有節點的最短路徑。

核心思想:以起始點為中心向外走訪(廣度優先搜尋的概念)，直到所有節點都被拜訪過為止。


Dijkstra演算法步驟:

首先任選某個節點當作出發點，接著從與其相鄰且尚未走訪過的節點當中，

選出一個與出發點距離最短的節點，把它新增至路徑中(更新最短路徑表)，再接著由此新加入的節點

向外擴展，找尋與其相鄰且尚未走訪過的節點，且距離出發點路徑最短，重複步驟更新最短路徑表，

直到所有的節點都被加入到路徑中。


Dijkstra演算法架構描述:

首先創一個空間用來記錄每個節點到與其相鄰的節點間的距離(透過程式碼中的helper函式做處理)

接著初始化一個array用來記錄已走訪過的節點(程式碼:path)、dict(程式碼:shortest)用來紀錄

起始點到當前節點的最短路徑長、dict(程式碼:previous)用來記錄當前節點的前一個節點、[[]]

(程式碼:pq)用來找出最短路徑的vertex。從起始點開始向外擴展，尋找與其相鄰且未拜訪過的節點

中，距離起始點距離最短的節點，再更新最短路徑表(shortest、previous)--> 此為程式碼中第二個

for迴圈中第一個for迴圈的部分，並且append到pq中，再透過pq找出最短路徑的vertex--> 此為程式

碼中最後一個迴圈的部分。

-----------------------------------------------------------------------------------

Kruskal演算法，又稱最小生成樹演算法，是用來是一種用來尋找最小生成樹的演算法。

什麼是最小生成樹? 

1. 是一顆樹 --> 無迴路、邊數為點數-1。

2. 是生成樹 --> 包含全部頂點、(頂點數-1)條邊都在圖裡。
                 
3. 邊的權重和最小。


Kruskal演算法步驟:

首先將每條邊的權重由小到大排序，每次都先挑選權重最小的那個邊，但要確保挑選到的那個邊如果

加入最小生成樹中時，不會形成loop(若會形成loop則捨棄那條邊)，重複上述挑選步驟，直到最小生

成樹中，有V-1條邊。

Kruskal演算法架構描述:

首先將每條邊的權重由小到大排序(程式碼:arr = sorted(list(zip(self.wet,self.edge))))

-->如此一來，每次就取arr[0]來處理。

另外為了要判斷是否會形成loop，因此要創一個空間紀錄每條邊的root(程式碼:self.root = {})

主程式分為5大情況:

1. 兩個input的root皆為空，統一指定成大的那個的root

2. 小的那個root為空，且大的那個的root存在，把小的那個root指定成大的input的root

3. 大的那個root為空，且小的那個的root存在，把大的那個root指定成小的input的root

4. root皆存在且不相等，把所有root=小的那個改成大的root(先處理非小的那個以外的)

5. root皆存在且相等(會產生loop)，不加入，進行recursive

流程圖

In [18]:
from IPython.display import Image
from IPython.core.display import HTML
Image(url= "https://github.com/imucici/my-learning-note/blob/master/%E5%9C%96%E7%89%87/%E6%9C%80%E7%9F%AD%E8%B7%AF%E5%BE%91.jpg?raw=true" ,width = 1000,height = 1000)

In [2]:
from IPython.display import Image
from IPython.core.display import HTML
Image(url= "https://github.com/imucici/my-learning-note/blob/master/%E5%9C%96%E7%89%87/MST.jpg?raw=true" ,width = 1000,height = 1000)

12/22先來研究程式碼範例是啥意思

self.graph_matrix這行感覺像上次寫hash table時，初始化self.data = [None] * capacity 一樣

--> 目的就是為了創造出相應的空間來讓我們存放計算後的結果

In [28]:
from collections import defaultdict 

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
    def printt(self):
        print(self.V)
        print(self.graph)
        print(self.graph_matrix)

In [29]:
Graph(6).printt()

6
[]
[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]


In [40]:
from collections import defaultdict 
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
    def printt(self):
        print(self.V)
        print(self.graph)
        d = np.matrix(self.graph_matrix)
        print(d)

In [41]:
Graph(9).printt()

9
[]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [55]:
from collections import defaultdict 
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
    def printt(self):
        print(self.V)
        print(self.graph)
        d = np.matrix(self.graph_matrix)
        print(d)
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s): #最短路徑
        for i in range(self.V):
            for j in range(self.V):
                self.graph_matrix[0][j] = self.graph[s][j]
        print(np.matrix(self.graph_matrix))
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [56]:
g = Graph(9)
g.graph = [[0,4,0,0,0,0,0,8,0],
           [4,0,8,0,0,0,0,11,0],
           [0,8,0,7,0,4,0,0,2],
           [0,0,7,0,9,14,0,0,0],
           [0,0,0,9,0,10,0,0,0],
           [0,0,4,14,10,0,2,0,0],
           [0,0,0,0,0,2,0,1,6],
           [8,11,0,0,0,0,1,0,7],
           [0,0,2,0,0,0,6,7,0]]

先print出來看看結果是不是跟我想要的一樣

In [60]:
g.Dijkstra(6)

[[0 0 0 0 0 2 0 1 6]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [7]:
from collections import defaultdict 
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
    def printt(self):
        print(self.V)
        print(self.graph)
        d = np.matrix(self.graph_matrix)
        print(d)
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s): #最短路徑
        
        for i in range(self.V):
            min_index = self.find_min_index(self.graph_matrix[i],[])
            print(min_index)
            
            for j in range(self.V):
                self.graph_matrix[0][j] = self.graph[s][j]
        print(np.matrix(self.graph_matrix))
        
        
        
    def find_min_index(self,a,Min):
        Min.append(a[0])
        for i in range(1,len(a)):
            if a[i] != 0 and a[i] < Min[0]:
                Min[0] = a[i]
        return i

In [5]:
g = Graph(9)
g.graph = [[0,4,0,0,0,0,0,8,0],
           [4,0,8,0,0,0,0,11,0],
           [0,8,0,7,0,4,0,0,2],
           [0,0,7,0,9,14,0,0,0],
           [0,0,0,9,0,10,0,0,0],
           [0,0,4,14,10,0,2,0,0],
           [0,0,0,0,0,2,0,1,6],
           [8,11,0,0,0,0,1,0,7],
           [0,0,2,0,0,0,6,7,0]]

In [9]:
from collections import defaultdict 


class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s): #最短路徑
        lst2 = self.helper()
        pq , path = [] , [s]
        shortest , previous = {} , {}
        for i in range(self.V):
            shortest[i] , previous[i] = None , None
        shortest[s] , previous[s] = 0 , None
        
        for k in range(self.V-1):
            a = lst2[path[-1]]
            for i in range(len(a)): #處理 shortest pervious (pq尚未按照路徑長排序)
                vertex = a[i][0]
                if vertex not in path:
                    total = a[i][-1] + shortest[path[-1]]
                    pq.append([vertex,total])
                    if shortest[vertex] == None:
                        shortest[vertex] = total
                        previous[vertex] = path[-1]
                    else:
                        if total < shortest[vertex]:
                            shortest[vertex] = total
                            previous[vertex] = path[-1]
            
            
            temp = None
            for j in range(len(pq)): #對pq排序
                if pq[j][0] not in path:
                    if temp == None:
                        temp = pq[j]
                    else:
                        if pq[j][-1] < temp[-1]:
                            temp = pq[j]

            path.append(temp[0])
            pq.remove(temp)
#             print("k=",k)
#             print("temp=",temp)
#             print("pq=",pq)
#             print("path=",path)
        print("shortest=",shortest)
        print("previous=",previous)
#             print()
        
        return shortest
    
    def helper(self): #每個點到與他相鄰的點的路徑長
        lst1 = []
        lst2 = [None]*self.V
        for i in range(self.V):
            for j in range(len(self.graph[i])):
                if self.graph[i][j] != 0 :
                    lst1.append([j,self.graph[i][j]])
            lst2[i] = lst1
            lst1 = []
        return lst2

In [13]:
g = Graph(9)
g.graph = [[0,4,0,0,0,0,0,8,0],
           [4,0,8,0,0,0,0,11,0],
           [0,8,0,7,0,4,0,0,2],
           [0,0,7,0,9,14,0,0,0],
           [0,0,0,9,0,10,0,0,0],
           [0,0,4,14,10,0,2,0,0],
           [0,0,0,0,0,2,0,1,6],
           [8,11,0,0,0,0,1,0,7],
           [0,0,2,0,0,0,6,7,0]]
g.Dijkstra(8)

shortest= {0: 14, 1: 10, 2: 2, 3: 9, 4: 16, 5: 6, 6: 6, 7: 7, 8: 0}
previous= {0: 1, 1: 2, 2: 8, 3: 2, 4: 5, 5: 2, 6: 8, 7: 8, 8: None}


{0: 14, 1: 10, 2: 2, 3: 9, 4: 16, 5: 6, 6: 6, 7: 7, 8: 0}

In [25]:
from collections import defaultdict 

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 

    def Dijkstra(self, s): #最短路徑
        lst2 = self.helper()
        
        path,pq = [s],[] # path用來記錄已走訪過的節點 ; pq用來找出最短路徑的vertex
        shortest , previous = {} , {}
        for i in range(self.V):
            shortest[i] , previous[i] = None , None
        shortest[s],previous[s] = 0 , None
        
        for i in range(self.V-1):
            a = lst2[path[-1]]
            for j in range(len(a)):
                vertex = a[j][0]
                if vertex not in path:
                    total = a[j][-1]+shortest[path[-1]]
                    if shortest[vertex] == None:
                        shortest[vertex] = total
                        previous[vertex] = path[-1]
                        pq.append([vertex,total])
                    else:
                        if total < shortest[vertex]:
#                             print("修改前，0到",vertex,"的最短距離是",shortest[vertex])
                            shortest[vertex] = total
#                             print("修改後，0到",vertex,"的最短距離是",shortest[vertex])
                            previous[vertex] = path[-1]
                            pq.append([vertex,total])
            
            temp = 1
            for k in range(len(pq)): #從pq中找出最短路徑的vertex
                if pq[k][0] not in path:
                    if temp == 1:
                        temp = pq[k]   
                    else:
                        if temp[-1] > pq[k][-1]:
                            temp = pq[k]
            
            path.append(temp[0])
            pq.remove(temp)
#             print("path=",path)
#             print("shortest=",shortest)
#             print("previous=",previous)
#             print()

        final = {}
        for i in range(self.V):
            final[str(i)] = shortest[i]

        return final
    
    def helper(self): #每個點到與他相鄰的點的路徑長
        lst1 = []
        lst2 = [None]*self.V
        for i in range(self.V):
            for j in range(len(self.graph[i])):
                if self.graph[i][j] != 0:
                    lst1.append([j,self.graph[i][j]])
            lst2[i] = lst1
            lst1 = []
        return lst2

In [26]:
g = Graph(9)
g.graph = [[0,4,0,0,0,0,0,8,0],
           [4,0,8,0,0,0,0,11,0],
           [0,8,0,7,0,4,0,0,2],
           [0,0,7,0,9,14,0,0,0],
           [0,0,0,9,0,10,0,0,0],
           [0,0,4,14,10,0,2,0,0],
           [0,0,0,0,0,2,0,1,6],
           [8,11,0,0,0,0,1,0,7],
           [0,0,2,0,0,0,6,7,0]]
g.Dijkstra(8)

{'0': 14, '1': 10, '2': 2, '3': 9, '4': 16, '5': 6, '6': 6, '7': 7, '8': 0}

最短路徑應該是正確了，接著寫Kruskal~

In [8]:
from collections import defaultdict 

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
        self.edge = []
        self.wet = []
        
    def addEdge(self,u,v,w): 
        self.edge.append([u,v])
        self.wet.append(w)
        
    def Kruskal(self):
        v , final , n = set() , {} ,0
        
        arr = sorted(list(zip(self.wet,self.edge))) #權重由小到大排
        print(arr)
        while n < len(arr):
            n+=1
            if len(v) == 0: 
                v.add(arr[0][1][0])
                v.add(arr[0][1][1])
                final[str(arr[0][1][0])+"-"+str(arr[0][1][1])] = arr[0][0]
                arr.pop(0)

            else:
                while len(arr) != 0 and arr[0][1][0] in v and arr[0][1][1] in v :
                    arr.pop(0)
                if len(arr) != 0 :
                    v.add(arr[0][1][0])
                    v.add(arr[0][1][1])
                    final[str(arr[0][1][0])+"-"+str(arr[0][1][1])] = arr[0][0]
        return final
            

In [9]:
g = Graph(9)
g.addEdge(0,1,4)
g.addEdge(0,7,8)
g.addEdge(1,7,11)
g.addEdge(1,2,8)
g.addEdge(7,8,7)
g.addEdge(7,6,1)
g.addEdge(2,8,2)
g.addEdge(8,6,6)
g.addEdge(2,3,7)
g.addEdge(2,5,4)
g.addEdge(6,5,2)
g.addEdge(3,5,14)
g.addEdge(4,3,9)
g.addEdge(5,4,10)
g.Kruskal()

[(1, [7, 6]), (2, [2, 8]), (2, [6, 5]), (4, [0, 1]), (4, [2, 5]), (6, [8, 6]), (7, [2, 3]), (7, [7, 8]), (8, [0, 7]), (8, [1, 2]), (9, [4, 3]), (10, [5, 4]), (11, [1, 7]), (14, [3, 5])]


{'7-6': 1, '2-8': 2, '6-5': 2, '0-1': 4, '2-3': 7, '4-3': 9}

尬的 以為4個點的正確就是寫完了= _ = 測個9個點的就錯了 @@

原來不能只判斷節點是否已存在於已遍歷過的array中，這樣整個遍歷完可能會發生點無法連起來的狀況....

思考一陣子後，想到當初老師上課在教的時候，判斷新加入的邊是否會形成loop時，是透過每次紀錄edge的相對應root(或稱parent)，因此決定從這個方向接下去寫，紀錄root並隨相對應的狀況更新root

In [7]:
from collections import defaultdict 

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
        self.edge = []
        self.wet = []
        self.root = {}
        self.final = {}
        self.n = 0
        
    def addEdge(self,u,v,w): 
        self.edge.append([u,v])
        self.wet.append(w)
        
    def Kruskal(self):
        arr = sorted(list(zip(self.wet,self.edge))) #權重由小到大排
        
        print(arr)
        
        for i in range(self.V):
            self.root[i] = None
            
        
        while self.n < self.V -1:
            self.helper(arr)
        
        return self.final
            
    def helper(self,arr):
        
        a = arr[0]
        
        s , b = min(a[1][0],a[1][1]) , max(a[1][0],a[1][1])
        
        det = True
        
        if self.root[s] == None and self.root[b] == None:
            self.root[s],self.root[b] = b,b
            self.n+=1
            
        elif self.root[s] == None and self.root[b] != None: 
            self.root[s] = self.root[b]
            self.n+=1
            
        elif self.root[b] == None and self.root[s] != None: 
            self.root[b] = self.root[s]
            self.n+=1
            
        elif self.root[s] != None and self.root[b] != None and self.root[s] != self.root[b]:
            for j in self.root:
                if self.root[j] == self.root[s]:
                    self.root[s] = self.root[b]
            self.n+=1
            
        elif self.root[s] != None and self.root[b] != None and self.root[s] == self.root[b]:
            det = False
            if self.root[s] == self.root[b]:
                arr.pop(0)
                self.helper(arr)
                
        if det == True:
            self.final[str(a[1][0])+"-"+str(a[1][1])] = a[0]
            arr.pop(0)
        

有了大方向後，程式碼寫起來就順手許多，丟個測值看看答案對不對

In [9]:
g = Graph(9)
g.addEdge(0,1,4)
g.addEdge(0,7,8)
g.addEdge(1,7,11)
g.addEdge(1,2,8)
g.addEdge(7,8,7)
g.addEdge(7,6,1)
g.addEdge(2,8,2)
g.addEdge(8,6,6)
g.addEdge(2,3,7)
g.addEdge(2,5,4)
g.addEdge(6,5,2)
g.addEdge(3,5,14)
g.addEdge(4,3,9)
g.addEdge(5,4,10)
g.Kruskal()

[(1, [7, 6]), (2, [2, 8]), (2, [6, 5]), (4, [0, 1]), (4, [2, 5]), (6, [8, 6]), (7, [2, 3]), (7, [7, 8]), (8, [0, 7]), (8, [1, 2]), (9, [4, 3]), (10, [5, 4]), (11, [1, 7]), (14, [3, 5])]


{'7-6': 1,
 '2-8': 2,
 '6-5': 2,
 '0-1': 4,
 '2-5': 4,
 '8-6': 6,
 '2-3': 7,
 '7-8': 7}

尬的，形成loop，照著程式碼的邏輯跑一次，發現原來錯誤是出在第四個條件式裡面， 當遇到root皆存在且不相等，原本的想法是把所有root=小的那個改成大的root，但是當小的那個input的root在最初就被改掉後(也就是說基準點被換掉)這樣就會造成一些edge的root無法隨之更改，因此就會出錯。

In [1]:
from collections import defaultdict 

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
        self.edge = []
        self.wet = []
        self.root = {} #紀錄每條邊的root
        self.final = {} #最後要return的
        self.n = 0 #等到執行 self.V-1次即停止
        
    def addEdge(self,u,v,w): 
        self.edge.append([u,v])
        self.wet.append(w)
        
    def Kruskal(self):
        arr = sorted(list(zip(self.wet,self.edge))) #權重由小到大排
        
        print(arr)
        
        for i in range(self.V):
            self.root[i] = None
            
        
        while self.n < self.V -1:
            self.helper(arr)
        
        return self.final
            
    def helper(self,arr):
        
        a = arr[0]
        
        s , b = min(a[1][0],a[1][1]) , max(a[1][0],a[1][1])
        
        det = True
        
        # 兩個input的root皆為空，統一指定成大的那個的root
        if self.root[s] == None and self.root[b] == None:
            self.root[s],self.root[b] = b,b
            print("兩者皆空",self.root)
            self.n+=1
        
        # 小的那個root為空，且大的那個的root存在，把小的那個root指定成大的input的root
        elif self.root[s] == None and self.root[b] != None: 
            self.root[s] = self.root[b]
            print("小的root為空，大的root存在",self.root)
            self.n+=1
        
        # 大的那個root為空，且小的那個的root存在，把大的那個root指定成小的input的root
        elif self.root[b] == None and self.root[s] != None: 
            self.root[b] = self.root[s]
            print("大的root為空，小的root存在",self.root)
            self.n+=1
            
        # root皆存在且不相等，把所有root=小的那個改成大的root
        # (先處理非小的那個以外的，等出了迴圈再處理小的那個)
        elif self.root[s] != None and self.root[b] != None and self.root[s] != self.root[b]:
            for j in range(len(self.root)):
                if j != s and self.root[j] == self.root[s]:
                    self.root[j] = self.root[b]
            self.root[s] = self.root[b]
            print("皆存在且不相等",self.root)
            self.n+=1
            
        # root皆存在且相等(會產生loop)，不加入(把那情況刪除)，進行recursive    
        elif self.root[s] != None and self.root[b] != None and self.root[s] == self.root[b]:
            det = False
            arr.pop(0)
            self.helper(arr)
                
        if det == True:
            self.final[str(a[1][0])+"-"+str(a[1][1])] = a[0]
            arr.pop(0)

In [3]:
g = Graph(9)
g.addEdge(0,1,4)
g.addEdge(0,7,8)
g.addEdge(1,7,11)
g.addEdge(1,2,8)
g.addEdge(7,8,7)
g.addEdge(7,6,1)
g.addEdge(2,8,2)
g.addEdge(8,6,6)
g.addEdge(2,3,7)
g.addEdge(2,5,4)
g.addEdge(6,5,2)
g.addEdge(3,5,14)
g.addEdge(4,3,9)
g.addEdge(5,4,10)
g.Kruskal()

[(1, [7, 6]), (2, [2, 8]), (2, [6, 5]), (4, [0, 1]), (4, [2, 5]), (6, [8, 6]), (7, [2, 3]), (7, [7, 8]), (8, [0, 7]), (8, [1, 2]), (9, [4, 3]), (10, [5, 4]), (11, [1, 7]), (14, [3, 5])]
兩者皆空 {0: None, 1: None, 2: None, 3: None, 4: None, 5: None, 6: 7, 7: 7, 8: None}
兩者皆空 {0: None, 1: None, 2: 8, 3: None, 4: None, 5: None, 6: 7, 7: 7, 8: 8}
小的root為空，大的root存在 {0: None, 1: None, 2: 8, 3: None, 4: None, 5: 7, 6: 7, 7: 7, 8: 8}
兩者皆空 {0: 1, 1: 1, 2: 8, 3: None, 4: None, 5: 7, 6: 7, 7: 7, 8: 8}
皆存在且不相等 {0: 1, 1: 1, 2: 7, 3: None, 4: None, 5: 7, 6: 7, 7: 7, 8: 7}
大的root為空，小的root存在 {0: 1, 1: 1, 2: 7, 3: 7, 4: None, 5: 7, 6: 7, 7: 7, 8: 7}
皆存在且不相等 {0: 7, 1: 7, 2: 7, 3: 7, 4: None, 5: 7, 6: 7, 7: 7, 8: 7}
大的root為空，小的root存在 {0: 7, 1: 7, 2: 7, 3: 7, 4: 7, 5: 7, 6: 7, 7: 7, 8: 7}


{'7-6': 1,
 '2-8': 2,
 '6-5': 2,
 '0-1': 4,
 '2-5': 4,
 '2-3': 7,
 '0-7': 8,
 '4-3': 9}

In [5]:
g = Graph(6)
g.addEdge(0,1,6)
g.addEdge(0,2,5)
g.addEdge(1,2,3)
g.addEdge(0,3,11)
g.addEdge(2,3,7)
g.addEdge(0,4,16)
g.addEdge(3,4,9)
g.addEdge(3,5,2)
g.addEdge(2,5,10)
g.Kruskal()

[(2, [3, 5]), (3, [1, 2]), (5, [0, 2]), (6, [0, 1]), (7, [2, 3]), (9, [3, 4]), (10, [2, 5]), (11, [0, 3]), (16, [0, 4])]
兩者皆空 {0: None, 1: None, 2: None, 3: 5, 4: None, 5: 5}
兩者皆空 {0: None, 1: 2, 2: 2, 3: 5, 4: None, 5: 5}
小的root為空，大的root存在 {0: 2, 1: 2, 2: 2, 3: 5, 4: None, 5: 5}
皆存在且不相等 {0: 5, 1: 5, 2: 5, 3: 5, 4: None, 5: 5}
大的root為空，小的root存在 {0: 5, 1: 5, 2: 5, 3: 5, 4: 5, 5: 5}


{'3-5': 2, '1-2': 3, '0-2': 5, '2-3': 7, '3-4': 9}

In [6]:
g = Graph(7)
g.addEdge(0,1,30)
g.addEdge(0,2,14)
g.addEdge(1,2,19)
g.addEdge(2,3,12)
g.addEdge(1,5,20)
g.addEdge(3,4,32)
g.addEdge(4,5,26)
g.addEdge(4,6,18)
g.addEdge(5,6,28)
g.Kruskal()

[(12, [2, 3]), (14, [0, 2]), (18, [4, 6]), (19, [1, 2]), (20, [1, 5]), (26, [4, 5]), (28, [5, 6]), (30, [0, 1]), (32, [3, 4])]
兩者皆空 {0: None, 1: None, 2: 3, 3: 3, 4: None, 5: None, 6: None}
小的root為空，大的root存在 {0: 3, 1: None, 2: 3, 3: 3, 4: None, 5: None, 6: None}
兩者皆空 {0: 3, 1: None, 2: 3, 3: 3, 4: 6, 5: None, 6: 6}
小的root為空，大的root存在 {0: 3, 1: 3, 2: 3, 3: 3, 4: 6, 5: None, 6: 6}
大的root為空，小的root存在 {0: 3, 1: 3, 2: 3, 3: 3, 4: 6, 5: 3, 6: 6}
皆存在且不相等 {0: 3, 1: 3, 2: 3, 3: 3, 4: 3, 5: 3, 6: 3}


{'2-3': 12, '0-2': 14, '4-6': 18, '1-2': 19, '1-5': 20, '4-5': 26}

大功告成!最後整統一下程式碼~

In [1]:
from collections import defaultdict 

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]  
                    for row in range(vertices)] 
        self.edge = []
        self.wet = []
        self.root = {} #紀錄每條邊的root
        self.final = {} #最後要return的
        self.n = 0 #等到執行 self.V-1次即停止
        
    def addEdge(self,u,v,w): 
        self.edge.append([u,v])
        self.wet.append(w)

    def Dijkstra(self, s): #最短路徑
        lst2 = self.helper_d()
        
        path,pq = [s],[] # path用來記錄已走訪過的節點 ; pq用來找出最短路徑的vertex
        shortest , previous = {} , {}
        for i in range(self.V):
            shortest[i] , previous[i] = None , None
        shortest[s],previous[s] = 0 , None
        
        for i in range(self.V-1):
            a = lst2[path[-1]]
            for j in range(len(a)):
                vertex = a[j][0]
                if vertex not in path:
                    total = a[j][-1]+shortest[path[-1]]
                    if shortest[vertex] == None:
                        shortest[vertex] = total
                        previous[vertex] = path[-1]
                        pq.append([vertex,total])
                    else:
                        if total < shortest[vertex]:
                            shortest[vertex] = total
                            previous[vertex] = path[-1]
                            pq.append([vertex,total])
            
            temp = 1
            for k in range(len(pq)): #從pq中找出最短路徑的vertex
                if pq[k][0] not in path:
                    if temp == 1:
                        temp = pq[k]   
                    else:
                        if temp[-1] > pq[k][-1]:
                            temp = pq[k]
            
            path.append(temp[0])
            pq.remove(temp)

        final = {}
        for i in range(self.V):
            final[str(i)] = shortest[i]

        return final
    
    def helper_d(self): #每個點到與他相鄰的點的路徑長
        lst1 = []
        lst2 = [None]*self.V
        for i in range(self.V):
            for j in range(len(self.graph[i])):
                if self.graph[i][j] != 0:
                    lst1.append([j,self.graph[i][j]])
            lst2[i] = lst1
            lst1 = []
        return lst2
    
    
    
    def Kruskal(self):
        arr = sorted(list(zip(self.wet,self.edge))) #權重由小到大排
        
        for i in range(self.V):
            self.root[i] = None
            
        
        while self.n < self.V -1:
            self.helper(arr)
        
        return self.final
            
    def helper(self,arr):
        
        a = arr[0]
        
        s , b = min(a[1][0],a[1][1]) , max(a[1][0],a[1][1])
        
        det = True
        
        # 兩個input的root皆為空，統一指定成大的那個的root
        if self.root[s] == None and self.root[b] == None:
            self.root[s],self.root[b] = b,b
            self.n+=1
        
        # 小的那個root為空，且大的那個的root存在，把小的那個root指定成大的input的root
        elif self.root[s] == None and self.root[b] != None: 
            self.root[s] = self.root[b]
            self.n+=1
        
        # 大的那個root為空，且小的那個的root存在，把大的那個root指定成小的input的root
        elif self.root[b] == None and self.root[s] != None: 
            self.root[b] = self.root[s]
            self.n+=1
            
        # root皆存在且不相等，把所有root=小的那個改成大的root
        # (先處理非小的那個以外的，等出了迴圈再處理小的那個)
        elif self.root[s] != None and self.root[b] != None and self.root[s] != self.root[b]:
            for j in range(len(self.root)):
                if j != s and self.root[j] == self.root[s]:
                    self.root[j] = self.root[b]
            self.root[s] = self.root[b]
            self.n+=1
            
        # root皆存在且相等(會產生loop)，不加入(把那情況刪除)，進行recursive    
        elif self.root[s] != None and self.root[b] != None and self.root[s] == self.root[b]:
            det = False
            arr.pop(0)
            self.helper(arr)
                
        if det == True:
            self.final[str(a[1][0])+"-"+str(a[1][1])] = a[0]
            arr.pop(0)
            
            
# 參考資料:
# 1. https://www.youtube.com/watch?v=9wV1VxlfBlI
# 2. https://wiki.mbalib.com/zh-tw/Dijkstra%E7%AE%97%E6%B3%95
# 3. https://codertw.com/%E7%A8%8B%E5%BC%8F%E8%AA%9E%E8%A8%80/434938/
# 4. https://www.youtube.com/watch?v=wuU4DDEUu1w
# 5. https://www.youtube.com/watch?v=71UQH7Pr9kU

In [2]:
g = Graph(7)
g.addEdge(0,1,30)
g.addEdge(0,2,14)
g.addEdge(1,2,19)
g.addEdge(2,3,12)
g.addEdge(1,5,20)
g.addEdge(3,4,32)
g.addEdge(4,5,26)
g.addEdge(4,6,18)
g.addEdge(5,6,28)
g.Kruskal()

{'2-3': 12, '0-2': 14, '4-6': 18, '1-2': 19, '1-5': 20, '4-5': 26}

In [3]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]

In [4]:
a.Dijkstra(0)

{'0': 0, '1': 4, '2': 12, '3': 19, '4': 21, '5': 11, '6': 9, '7': 8, '8': 14}